server {
    listen 80;

    location /items {
        proxy_pass http://web:5000;
    }

    location /health/ {
        proxy_pass http://web:5000;
    }

    location = / {
        proxy_pass http://web:5000;
    }

    location / {
        return 403;
    }
}
